#七牛配置
qiniu:
      AccessKey: T2p0exKwyYjbxlO1g1D0uI1sf8N8gfbC_KPIbq2R
      SecretKey: CkTFYoVgCSyCsCzovYm2URrF6LihzfEO4GD5kYAC
      Bucket: images

#mybatis驼峰注解开启
mybatis:
      configuration:
            map-underscore-to-camel-case: true

